- name: Deploy Provider resource
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      metadata:
        name: "{{ provider_name }}"
        namespace: "{{ provider_namespace }}"
      spec:
        secret:
          name: "{{ vmware_credentials }}"
          namespace: "{{ provider_namespace }}"
        settings:
          vddkInitImage: 'icr.io/rhdp/vddk:latest'
        type: vsphere
        url: "{{ vmware_url }}"
